language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: heroku-workshop-vivianxu1230
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: mqowXBeBMowYs/crm1vV7Vs2+xaFwQ6YtIU2Wn/YsR9z4crDTp9JGn7Fb+vXTNtFpVWAwgDQRsr/zfI9DReKZGvaNbJJ9ZjkIDveZLvU/AoyPxaUd5D8JVSY50Ks1fRsnh2qLSdfgx6+Tv63rkgQe0s6Cyq7JIBiqb+rug4V3+bJSPwAgPIcMzI5JbejR4GsiaJZEtAWC7qQrXSGxpsw8dst+XINaBmOENeWDby5rMWdMHEevr2XJOvTt9M8LW9b+je8rgWpYKKtAYYFaE3ZPHt0T+Tmevq9Rsazxo/feVpOfxN7b4+T76mEO4H9KLJxph3sa5VWBnqgBwRZ0+xhqtt4VtiFf198LGyWyOEkFGx/2gQszcwIw9vTDG5RceDTPy8zKkXDdvvs6MxQRJUsmlk0z1x9BYePXF8Hyl+S7xzHoKzty3KDRNjWccRzmazmQprmXl5WHltkBizqF7pc2/tU5QO6Ev6SOYhU0asq4JT+mfbuUEEn0bh0v5MEEUBaRTF6sa08Op44ur556qH1v5iz7vHewi7Vt7coZx47haY+AGvfH06svBs3iJxIHtR40K978nf/L7CFSR4bnPUZjN2ZG4qlVNwmk8TRHpiEwHKymu2lQ2vGnqfnd3GANQPMKsaiyZOKDxNxgRmuRX6A1xbP/TkQyt1zRi9DC18brwc=
